
run:
  timeout: 3m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

    - errorlint
    - nilerr

    - gocritic
    - exhaustive
    - revive

    - misspell