services:
  - type: web
    name: avito-recap-demo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: STORAGE_BACKEND
        value: memory
