upstream api_backend {
    server api:8080;
    keepalive 32;
}

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript text/javascript
        application/xml text/xml image/svg+xml;

    # Общая сеть в докере дает возможность указывать хосты через имена
    location /api/ {
        proxy_pass http://api_backend/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Кэшируем статические файлы фронта
    location ~* \.(?:css|js|mjs|woff2?|ttf|eot|svg|png|jpe?g|gif|ico|webp|avif)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Может обновится при деплое - и обновит за собой статику
    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    # Простой указатель под файлы фронта
    location / {
        try_files $uri $uri/ /index.html;
    }
}
